name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      password: ${{ secrets.UPA_PASSWORD }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: build
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn
      - run: yarn build
      - run: yarn test
      - name: scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.UPA_HOST }}
          username: ${{ secrets.UPA_USERNAME }}
          password: ${{ secrets.UPA_PASSWORD }}
          port: ${{ secrets.UPA_PORT }}
          source: "build/*"
          target: "tempdeploydir"
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.UPA_HOST }}
          username: ${{ secrets.UPA_USERNAME }}
          password: ${{ secrets.UPA_PASSWORD }}
          port: ${{ secrets.UPA_PORT }}
          script_stop: false
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -rf ~/tempdeploydir/build/* /var/www/html/
            sudo chmod 755 -R /var/www/html/
            sudo chown -R root:root /var/www/html/
            rm -rf ~/tempdeploydir
